title = "OpenTelemetry"
baseURL = "https://opentelemetry.io"
disableKinds = ["taxonomy", "taxonomyTerm"]

[blackfriday]
hrefTargetBlank = true

[params]
tagline = "Effective observability requires high-quality telemetry"
sub_tagline = "**OpenTelemetry** makes robust, portable telemetry a built-in feature of cloud-native software."
sub_description = "**OpenTelemetry** provides a single set of APIs, libraries, agents, and collector services to capture distributed traces and metrics from your application. You can analyze them using Prometheus, Jaeger, and other observability tools."
font_awesome_version = "5.8.1"

[params.logos]
hero = "opentelemetry-horizontal-color.png"
cncf = "cncf.png"

[[params.social]]
name = "GitHub"
url = "https://github.com/open-telemetry/"
color = "black"
icon = "fab fa-github"

[[params.social]]
name = "Twitter"
url = "https://twitter.com/opentelemetry"
color = "twitter"
icon = "fab fa-twitter"

[[params.social]]
name = "Gitter"
url = "https://gitter.im/open-telemetry/community"
color = "gitter"
icon = "fab fa-gitter"

[[params.social]]
name = "Medium"
url = "https://medium.com/opentelemetry"
color = "light"
icon = "fab fa-medium"

[[params.social]]
name = "Mailing list"
url = "https://lists.cncf.io/g/cncf-opentelemetry-community"
color = "info"
icon = "far fa-envelope"

[[params.fonts]]
name = "Noto Sans"
sizes = [300,400,600,700]
type = "sans_serif"

[[params.links]]
name = "About"
localUrl = "/about"

[[params.links]]
name = "Get Started"
localUrl = "/get-started"

[menu]

[[menu.docs]]
    name = "JavaScript"
    url = "https://open-telemetry.github.io/opentelemetry-js/"

[[menu.docs]]
    name = "Go"
    url = "https://github.com/open-telemetry/opentelemetry-go/blob/master/README.md"

[[ menu.docs ]]
    name = "Python"
    url = "https://opentelemetry-python.readthedocs.io/"

[[ menu.docs ]]
    name = "Java"
    url = "https://github.com/open-telemetry/opentelemetry-java/blob/master/QUICKSTART.md"

[[ menu.docs ]]
    name = "Erlang"
    url = "https://github.com/open-telemetry/opentelemetry-erlang/blob/master/README.md"

[[ menu.docs ]]
    name = "Collector"
    url = "https://github.com/open-telemetry/opentelemetry-collector/blob/master/README.md"

[[ menu.docs ]]
    name = "C++"
    url = "https://github.com/open-telemetry/opentelemetry-cpp/blob/master/README.md"

[[ menu.docs ]]
    name = "Rust"
    url = "https://github.com/open-telemetry/opentelemetry-rust/blob/master/README.md"

[[ menu.docs ]]
    name = "Ruby"
    url = "https://github.com/open-telemetry/opentelemetry-ruby/blob/master/README.md"

[[ menu.docs ]]
    name = "C#"
    url = "https://github.com/open-telemetry/opentelemetry-dotnet/blob/master/README.md"
